### ISSUE TITLE
MacOS zooming and locating problem

### ISSUE THREAD

**Issue by ChuyanFu** [GRPMIPSVisualizer/Visualization#9]
The locations of some of the SVG components in safari are slightly different from which in other browsers. 
Zooming in safari has very high latency.

**Comment by IRIS0113** [comment]
The problem with Safari is that you can only change the length of the transform path every time you refresh your CSS, so I chose to disable zooming while the Safari animation is playing.

**Comment by ChuyanFu** [comment]
Fixed by loading the lines in register table after the whole website has been successfully loaded!
